db:
  host: localhost
  port: 5432
  name: pgisrauditlog
  username: postgres
  password: postgres

batch:
  archivingCron: 0 * * * * *
  output-directory: json/outputs/archives.json

spring:
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect
            jdbc:
              lob:
                non_contextual_creation: true
